name: tests

on:
  push:
    branches:
      - main
      - release
  pull_request: {}

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: g++-12

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.25.2
          ninjaVersion: 1.13.1

      - name: Run CMake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -GNinja -DKokkos_ENABLE_THREADS=ON -DKokkos_ENABLE_SERIAL=ON ../

      - name: Build
        run: cd build; cmake --build . -- -j2

      - name: Run Tests
        run: cd build; ./RunTests --kokkos-num-threads=2 --reporter junit -o test-results.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "Test Results"
          files: build/test-results.xml
